//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DevF_LABS.Language.Presentation.Controllers {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class XssController {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal XssController() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("DevF_LABS.Language.Presentation.Controllers.XssController", typeof(XssController).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Application.
        /// </summary>
        public static string Global_Application {
            get {
                return ResourceManager.GetString("Global_Application", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Example.
        /// </summary>
        public static string Global_Example {
            get {
                return ResourceManager.GetString("Global_Example", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unvalid GReCaptcha!.
        /// </summary>
        public static string Global_GReCaptcha {
            get {
                return ResourceManager.GetString("Global_GReCaptcha", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OK.
        /// </summary>
        public static string Global_OK {
            get {
                return ResourceManager.GetString("Global_OK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search Button.
        /// </summary>
        public static string Global_SearchButton {
            get {
                return ResourceManager.GetString("Global_SearchButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unauthrozied operation!.
        /// </summary>
        public static string Global_Unauthorize {
            get {
                return ResourceManager.GetString("Global_Unauthorize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Auth.
        /// </summary>
        public static string Recep_YeniKeyu {
            get {
                return ResourceManager.GetString("Recep_YeniKeyu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to When translating into Turkish, even if it means &apos;Reflected&apos; or &apos;Mirrored&apos;, we can say that it is harmless among the types of Reflected type XSS..
        /// </summary>
        public static string RXSS_Description_P1 {
            get {
                return ResourceManager.GetString("RXSS_Description_P1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reflected XSS is a non-persistent and only a weakness for the user running the malicious script..
        /// </summary>
        public static string RXSS_Description_P2 {
            get {
                return ResourceManager.GetString("RXSS_Description_P2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to In addition, this type of XSS is the most common type of XSS..
        /// </summary>
        public static string RXSS_Description_P3 {
            get {
                return ResourceManager.GetString("RXSS_Description_P3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to What Is Reflected XSS(Cross Site Scripting) ?.
        /// </summary>
        public static string RXSS_Description_WhatIsXSS {
            get {
                return ResourceManager.GetString("RXSS_Description_WhatIsXSS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to In its simplest form it can be tested with Reflected XSS.
        /// </summary>
        public static string RXSS_Scenario_1_P1 {
            get {
                return ResourceManager.GetString("RXSS_Scenario_1_P1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clicked Alert Button!.
        /// </summary>
        public static string RXSS_Scenario_1_P1_Alert {
            get {
                return ResourceManager.GetString("RXSS_Scenario_1_P1_Alert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to So if the malicious script can be run in any way on the browser, Reflected XSS is there..
        /// </summary>
        public static string RXSS_Scenario_1_P2 {
            get {
                return ResourceManager.GetString("RXSS_Scenario_1_P2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To better understand the subject, please review the example on the Example 2 tab..
        /// </summary>
        public static string RXSS_Scenario_1_P3 {
            get {
                return ResourceManager.GetString("RXSS_Scenario_1_P3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to World Of Scripts.
        /// </summary>
        public static string RXSS_Scenario_1_WorldOfScripts {
            get {
                return ResourceManager.GetString("RXSS_Scenario_1_WorldOfScripts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Many of today&apos;s websites provide users a quick way the information in the website with the search button..
        /// </summary>
        public static string RXSS_Scenario_2_P1 {
            get {
                return ResourceManager.GetString("RXSS_Scenario_2_P1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to When the search is made based on the number of characters entered in the last time, and Reflected XSS is unavoidable when the value entered immediately after is reflected on the screen! .
        /// </summary>
        public static string RXSS_Scenario_2_P2 {
            get {
                return ResourceManager.GetString("RXSS_Scenario_2_P2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The searched word is shown on the screen, enter the desired phrase when the &apos;Search!&apos; button is triggered in the textbox below.
        /// </summary>
        public static string RXSS_Scenario_2_P3 {
            get {
                return ResourceManager.GetString("RXSS_Scenario_2_P3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Instead of a script, you can try it out first with bold(&amp;lt;b /&amp;gt;) or italic(&amp;lt;i /&amp;gt;) HTML tags..
        /// </summary>
        public static string RXSS_Scenario_2_P4 {
            get {
                return ResourceManager.GetString("RXSS_Scenario_2_P4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to As you can see, the searched word will be written in bold..
        /// </summary>
        public static string RXSS_Scenario_2_P5 {
            get {
                return ResourceManager.GetString("RXSS_Scenario_2_P5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Finally, when we test that there is no tag restriction, we can create an example for Reflected XSS..
        /// </summary>
        public static string RXSS_Scenario_2_P6 {
            get {
                return ResourceManager.GetString("RXSS_Scenario_2_P6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to As you can see, you will see that the script written in the Textbox field works..
        /// </summary>
        public static string RXSS_Scenario_2_P7 {
            get {
                return ResourceManager.GetString("RXSS_Scenario_2_P7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Searching Word:.
        /// </summary>
        public static string RXSS_Scenario_2_P8 {
            get {
                return ResourceManager.GetString("RXSS_Scenario_2_P8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter Search Word ....
        /// </summary>
        public static string RXSS_Scenario_2_P8_Input {
            get {
                return ResourceManager.GetString("RXSS_Scenario_2_P8_Input", resourceCulture);
            }
        }
    }
}
